const wikiImage = (path) => `https://static.wikia.nocookie.net/bee-swarm-simulator/images/${path}`;

const enemy = (name, image, type, description, behavior, drops, respawn) => ({ name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'), image: wikiImage(image), type, description, behavior, drops, respawn });

export const enemies = [
  enemy('Ladybug', '3/38/Ladybug.png/revision/latest?cb=20200404010052', 'Common enemy', 'A small red enemy found across early and mid-game fields.', 'It walks toward the player and attacks at close range.', 'Treats, honey, and field loot', '5 minutes'),
  enemy('Rhino Beetle', '4/48/Rhino_Beetle.png/revision/latest?cb=20200404010143', 'Common enemy', 'A sturdy early-game enemy with a horn charge.', 'It charges and bumps the player while defending its field.', 'Treats, honey, and field loot', '5 minutes'),
  enemy('Spider', '8/84/Spider.png/revision/latest?cb=20180911055942', 'Common enemy', 'A white enemy that guards the Spider Field.', 'It moves quickly and attacks the player from close range.', 'Treats, honey, and field loot', '10 minutes'),
  enemy('Scorpion', 'a/ab/Scorpion.png/revision/latest?cb=20180413021814', 'Common enemy', 'A red enemy that guards the Rose Field and attacks aggressively.', 'It chases the player and uses its stinger at close range.', 'Treats, honey, and field loot', '5 minutes'),
  enemy('Mantis', 'a/a2/Mantis%281%29.png/revision/latest?cb=20180407163701', 'Common enemy', 'A green enemy found in several fields throughout the mountain.', 'It attacks with sweeping strikes and can pressure the player at close range.', 'Treats, honey, and field loot', '10 minutes'),
  enemy('Werewolf', 'f/f5/Werewolf.png/revision/latest?cb=20180413023405', 'Common enemy', 'A powerful enemy found in the Werewolf Cave.', 'It pursues the player and deals heavy melee damage.', 'Treats, honey, and field loot', '10 minutes'),
  enemy('King Beetle', '1/13/King_Beetle.png/revision/latest?cb=20200819021637', 'Boss', 'A recurring boss hidden beneath the Clover Field.', 'It has high health, attacks nearby players, and rewards a successful defeat with boss loot.', 'Treats, honey, amulets, and boss loot', '24 hours'),
  enemy('Tunnel Bear', 'e/e8/Tunnel_Bear.png/revision/latest?cb=20180728153853', 'Boss', 'A major boss found in the Tunnel beneath the Clover Field.', 'It attacks with strong close-range hits and has a large health pool.', 'Treats, honey, tickets, and boss loot', '48 hours'),
  enemy('Stump Snail', '2/23/Stump_Snail.png/revision/latest?cb=20181207154342', 'Boss', 'A huge boss that occupies the Stump Field.', 'It has enormous health and remains in the field until defeated.', 'Treats, honey, amulets, and boss loot', '96 hours'),
  enemy('Coconut Crab', '4/47/Coconut_Crab.png/revision/latest?cb=20211004171659', 'Boss', 'A high-level boss that guards Coconut Field.', 'It attacks with claws and coconut projectiles while defending its field.', 'Treats, honey, tropical loot, and boss loot', '36 hours'),
  enemy('Vicious Bee', '1/1f/Vicious_Bee.png/revision/latest?cb=20200404000135', 'Event boss', 'A rare event enemy that can appear in several fields.', 'It flies around the field, attacks with spikes, and drops valuable stingers when defeated.', 'Stingers, honey, treats, and rare loot', '30 minutes'),
  enemy('Stick Bug', '1/13/Stick_Bug.png/revision/latest?cb=20210622231112', 'Boss challenge', 'A challenge boss that leads the player through multiple fields.', 'Its challenge has stages, changing locations and difficulty as the player progresses.', 'Amulets, honey, tokens, and challenge rewards', 'Challenge cooldown varies'),
];

const mobDetails = {
  'Ladybug': { overview: 'Ladybugs are common red mobs that protect several early and mid-game fields. They are approachable targets for collecting early battle rewards and building combat progress.', behavior: 'A Ladybug walks toward the player and attacks at close range. Its predictable movement makes it a useful first combat target for a developing hive.', drops: 'Ladybugs always provide their normal battle reward, honey, and a token circle after defeat. Their possible Ticket drop has a 2% base chance, and Loot Luck increases that drop chance.', luck: 'At 0% Loot Luck the Ticket chance is 2%. At +100% Loot Luck, the wiki formula gives two rolls, making the chance 3.96%.', respawn: '5 minutes (4 minutes 15 seconds with Gifted Vicious Bee)' },
  'Rhino Beetle': { overview: 'Rhino Beetles are sturdy early-game mobs found in several fields. They are useful for battle points, honey, and early blue-field loot.', behavior: 'A Rhino Beetle charges and bumps the player while defending its field. Staying mobile helps the hive avoid its direct attack.', drops: 'Rhino Beetles provide battle rewards, honey, and possible Tickets, Blueberries, and Gumdrops. The Ticket drop has a 2% base chance, while the other possible drops are affected by Loot Luck.', luck: 'At 0% Loot Luck the Ticket chance is 2%, becoming 3.96% at +100% Loot Luck. The wiki lists the other item chances as Loot Luck affected without giving one fixed percentage.', respawn: '5 minutes (4 minutes 15 seconds with Gifted Vicious Bee)' },
  'Spider': { overview: 'The Spider guards Spider Field and is one of the first mobs with a longer respawn cycle. Defeating it provides stronger battle rewards than the earliest field mobs.', behavior: 'The Spider moves quickly and attacks at close range. It can chase the player beyond its field, so movement and bee attack both matter.', drops: 'The Spider can drop Tickets and Gumdrops in addition to its normal honey and battle rewards. Its Ticket drop has a 25% base chance and is affected by Loot Luck.', luck: 'At 0% Loot Luck the Ticket chance is 25%. At +100% Loot Luck, the two-roll chance is 43.75% using the wiki Loot Luck formula.', respawn: '30 minutes (25 minutes 30 seconds with Gifted Vicious Bee)' },
  'Scorpion': { overview: 'Scorpions are red mobs that guard Rose Field and reward players with red-field materials. They are more dangerous than Ladybugs because they combine aggressive pursuit with a longer timer.', behavior: 'A Scorpion chases the player and attacks with its stinger at close range. Red pollen and attack-focused bees help clear it efficiently.', drops: 'Scorpions guarantee battle points and honey, then can provide Tickets, Gumdrops, and Strawberries. The Ticket chance is 2/15, or about 13.33%, while Loot Luck affects the item drops marked by the wiki.', luck: 'At 0% Loot Luck the Ticket chance is about 13.33%. At +100% Loot Luck, two independent rolls would give about 24.89% if that drop is treated as Loot Luck affected.', respawn: '20 minutes (17 minutes with Gifted Vicious Bee)' },
  'Mantis': { overview: 'Mantis mobs appear in multiple mountain fields and offer useful battle rewards. They are a mid-level target that can be farmed repeatedly while traveling between fields.', behavior: 'A Mantis uses sweeping close-range attacks and pressures players who stand still. Keeping bees attacking while moving around it reduces the danger.', drops: 'Mantis mobs provide normal honey and battle rewards, with possible Tickets and Gumdrops. The Ticket drop has a 20% base chance and is increased by Loot Luck.', luck: 'At 0% Loot Luck the Ticket chance is 20%. At +100% Loot Luck, the two-roll chance is 36% using the wiki formula.', respawn: '20 minutes (17 minutes with Gifted Vicious Bee)' },
  'Werewolf': { overview: 'The Werewolf is a strong cave mob with a larger reward table than common field enemies. It is a good target for players who can handle heavier melee damage.', behavior: 'The Werewolf pursues the player and deals heavy close-range damage. Its cave location limits room to maneuver, so attack power and quick collection are valuable.', drops: 'Werewolves provide honey and battle rewards, with possible Tickets, Gumdrops, and Silver Eggs. The Ticket drop has a 50% base chance and is affected by Loot Luck.', luck: 'At 0% Loot Luck the Ticket chance is 50%. At +100% Loot Luck, the two-roll chance becomes 75%.', respawn: '1 hour (51 minutes with Gifted Vicious Bee)' },
  'King Beetle': { overview: 'King Beetle is a boss hidden beneath Clover Field and offers one of the earliest boss encounters. Its defeat can provide a King Beetle Amulet as well as a larger reward payout.', behavior: 'King Beetle has high health and attacks players near the center of its lair. Bees with strong attack shorten the fight and reduce the time spent waiting for the next cycle.', drops: 'King Beetle always gives its battle reward, honey, and other possible loot. The King Beetle Amulet has a fixed 1/7 chance, about 14%, and the wiki states Loot Luck does not improve that amulet chance.', luck: 'At 0% Loot Luck the amulet chance is about 14%. With Loot Luck the amulet remains about 14%, while other eligible drops can become more likely.', respawn: '24 hours (20 hours 24 minutes with Gifted Vicious Bee)' },
  'Tunnel Bear': { overview: 'Tunnel Bear is a boss located in the tunnel beneath the early mountain area. It has a large health pool and gives a substantial reward table when defeated.', behavior: 'Tunnel Bear attacks with strong close-range hits while the player fights through its tunnel. Its narrow arena makes sustained bee damage and careful movement important.', drops: 'Tunnel Bear drops honey, treats, Gumdrops, Tickets, and other possible boss rewards. The wiki describes the possible reward quantities as Loot Luck affected rather than assigning one universal percentage to every item.', luck: 'The base chance differs by item and reward table, so there is no single Tunnel Bear drop percentage. Loot Luck adds rolls according to the wiki formula, while guaranteed rewards remain guaranteed.', respawn: '48 hours (40 hours 48 minutes with Gifted Vicious Bee)' },
  'Stump Snail': { overview: 'Stump Snail is a huge boss that occupies Stump Field until defeated. Its enormous health makes it a long-term combat goal and a major source of rewards.', behavior: 'The Snail remains in its field and has extremely high health. Players usually damage it over repeated visits rather than finishing the fight in one short session.', drops: 'Stump Snail guarantees an amulet and is the only mob that guarantees Glue, alongside honey, Gumdrops, and other possible loot. The wiki lists additional item chances through its reward table rather than one universal drop percentage.', luck: 'Guaranteed amulet and Glue remain guaranteed at 0% and with Loot Luck. Other eligible drops use their table chances and become more likely when Loot Luck grants extra rolls.', respawn: '96 hours (81 hours 36 minutes with Gifted Vicious Bee)' },
  'Coconut Crab': { overview: 'Coconut Crab is a high-level boss guarding Coconut Field. Its reward quality and quantity can depend on how quickly the player defeats it.', behavior: 'The Crab attacks with claws and coconut projectiles while defending its field. Players must balance movement, damage, and token collection because the fight can punish standing in one place.', drops: 'Coconut Crab provides honey, treats, Gumdrops, tropical materials, and other boss rewards. The wiki notes that some reward quality and quantity depends on defeat speed, while eligible drops are also influenced by Loot Luck.', luck: 'There is no single public percentage for the full Coconut Crab reward table. Loot Luck improves eligible drop rolls, but it does not replace the separate effect of defeating the Crab quickly.', respawn: '36 hours (30 hours 36 minutes with Gifted Vicious Bee)' },
  'Vicious Bee': { overview: 'Vicious Bee is a rare event boss that can appear in several fields. It is highly valuable because defeating it can provide Stingers and helps players progress toward event-focused rewards.', behavior: 'Vicious Bee flies around the field and attacks with spikes. Its movement makes precise positioning and strong bee attack important during the encounter.', drops: 'Vicious Bee drops Stingers, honey, treats, and other rare loot after defeat. The exact reward table can vary, and Loot Luck improves eligible item rolls rather than guaranteeing a Stinger.', luck: 'The wiki does not give one universal percentage for every Vicious Bee drop. At higher Loot Luck, eligible drops receive extra rolls using 1 - ((1 - base chance) ^ luck), while guaranteed rewards remain unchanged.', respawn: '30 minutes; Gifted Vicious Bee reduces this to 25 minutes 30 seconds, 4 minutes 30 seconds faster' },
  'Stick Bug': { overview: 'Stick Bug is a multi-stage boss challenge rather than a simple field mob. Its difficulty and rewards change as the challenge moves through different fields.', behavior: 'Stick Bug progresses through stages and changes locations as the challenge continues. Players need coordinated damage and movement to keep up with the changing arena.', drops: 'Stick Bug can award amulets, honey, tokens, and challenge rewards after the run. Its reward quality depends on the challenge result, so the wiki does not provide one universal drop percentage for every reward.', luck: 'Because Stick Bug rewards are tied to challenge performance and tables, there is no single base-versus-Loot-Luck percentage. Loot Luck affects eligible item rolls when the reward table allows it, but it does not replace score-based rewards.', respawn: 'Challenge cooldown varies' },
};

enemies.forEach((enemyData) => Object.assign(enemyData, mobDetails[enemyData.name]));
export const enemyBySlug = (slug) => enemies.find((enemyData) => enemyData.slug === slug);
